name: release

on:
  push:
    branches: [master]

jobs:
  goreleaser:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup dependencies
        uses: actions/setup-go@v2
      - name: release dry run
        run: make release-dry-run
      - uses: go-semantic-release/action@v1
        id: semantic
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update tags
        if: steps.semantic.outputs.version != ''
        run: |
          TAG=v${{ steps.semantic.outputs.version }}
          git push origin :refs/tags/${TAG}
          git tag -fa ${TAG} -m "release v${{ steps.semantic.outputs.version }}"
          git push origin ${TAG}
      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
      - name: release publish
        run: make release
